version: '3.8'

services:
  # Cấu hình cho Backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - shop-network

  # Cấu hình cho Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # Frontend cần đợi Backend chạy trước
    depends_on:
      - backend
    # Cho phép hot-reload (sửa code máy thật, docker tự cập nhật)
    volumes:
      - ./frontend/src:/app/src
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge